package adapter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// FrameworkSupport defines the contract for framework-specific automate
// artefact generation. Implementations are registered per framework name
// in frameworkRegistry. Core BuiltinAutomate looks up support by framework
// and delegates generation -- it never interprets framework-specific values
// such as file extensions, output paths, or skeleton content.
//
// BUG-108 / ADR-022: framework-neutral core, adapter-owned framework behaviour.
type FrameworkSupport interface {
	// Extension returns the file extension for generated artefacts
	// (e.g. ".bats", ".spec.ts", ".Tests.ps1"). Includes the leading dot.
	Extension() string

	// OutputDir returns the project-relative output directory for artefacts,
	// given the work-item subdir (e.g. "my-feature/" or "a/b/").
	// The returned path uses forward slashes and is relative to the project root.
	OutputDir(subdir string) string

	// GenerateSkeleton writes the skeleton artefact file to outPath.
	// tcID is the test case ID (e.g. "tc-aaa12345"), projectRoot is the
	// absolute project root, and outPath is the absolute path where the
	// skeleton should be written. The caller ensures the parent directory
	// exists before calling.
	GenerateSkeleton(tcID, projectRoot, outPath string) error
}

// frameworkRegistry maps framework names to their FrameworkSupport
// implementation. Adding a new framework is a single registry entry --
// core BuiltinAutomate never needs to change.
//
// BUG-111: registered "playwright" to unblock --preset playwright. The
// generated artefact is a deliberately skeletal one-file-per-TC .spec.ts
// (ENH-112 is the ENH for richer Playwright integration).
var frameworkRegistry = map[string]FrameworkSupport{
	"bats":       &BATSSupport{},
	"playwright": &PlaywrightSupport{},
}

// LookupFrameworkSupport returns the FrameworkSupport for the given framework
// name, or nil if no support is registered. Core code uses this to determine
// whether automate can proceed for the requested framework.
func LookupFrameworkSupport(framework string) FrameworkSupport {
	return frameworkRegistry[framework]
}

// BATSSupport implements FrameworkSupport for the BATS testing framework.
// It owns the BATS file extension, output path convention, helper loading
// depth, and skeleton template content.
type BATSSupport struct{}

// Extension returns ".bats".
func (b *BATSSupport) Extension() string {
	return ".bats"
}

// OutputDir returns the project-relative BATS output directory.
// BATS artefacts live under test/acceptance/{subdir}/.
func (b *BATSSupport) OutputDir(subdir string) string {
	base := "test/acceptance"
	subdir = strings.TrimRight(subdir, "/")
	if subdir == "" {
		return base
	}
	return base + "/" + subdir
}

// GenerateSkeleton writes a BATS skeleton file to outPath. The skeleton
// includes setup_file(), setup(), a placeholder @test, and teardown(). The
// helper load path is computed relative to the project root based on the
// artefact's nesting depth.
func (b *BATSSupport) GenerateSkeleton(tcID, projectRoot, outPath string) error {
	// Compute project-relative path for depth calculation.
	relPath, err := filepath.Rel(projectRoot, outPath)
	if err != nil {
		return fmt.Errorf("computing relative path for skeleton: %w", err)
	}
	relPath = filepath.ToSlash(relPath)

	// Depth: count directory segments in the artefact's relative directory.
	// test/acceptance/my-feature/tc-xxx.bats -> dir = test/acceptance/my-feature -> 3 segments -> "../../.."
	dir := filepath.ToSlash(filepath.Dir(relPath))
	segments := strings.Split(dir, "/")
	dotdots := make([]string, len(segments))
	for i := range dotdots {
		dotdots[i] = ".."
	}
	depth := strings.Join(dotdots, "/")

	skeleton := fmt.Sprintf(`#!/usr/bin/env bats

# Auto-generated by gtms automate --adapter agent-automate
# Test case: %s

setup_file() {
    export PROJECT_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/%s" && pwd)"
    load "$PROJECT_ROOT/test/test_helper/common-setup.bash"
}

setup() {
    _common_setup
}

@test "%s: <describe what this test validates>" {
    # TODO: fill in the test body
    skip "skeleton -- not yet implemented"
}

teardown() {
    :
}
`, tcID, depth, tcID)

	return os.WriteFile(outPath, []byte(skeleton), 0644)
}

// PlaywrightSupport implements FrameworkSupport for the Playwright testing
// framework. BUG-111: deliberately skeletal one-file-per-TC starter; ENH-112
// will add richer Playwright integration (shared-file selection, append mode,
// JUnit parsing). Owns the .spec.ts extension, the gtms/scripts/playwright
// output path, and a minimal Playwright skeleton that stamps the TC ID into
// the test title so per-TC artefacts can be disambiguated.
type PlaywrightSupport struct{}

// Extension returns ".spec.ts".
func (p *PlaywrightSupport) Extension() string {
	return ".spec.ts"
}

// OutputDir returns the project-relative Playwright output directory.
// Playwright artefacts live under gtms/scripts/playwright/{subdir}/ so the
// playwright-runner.sh execute adapter can resolve them by TC ID without
// colliding with the BATS test/acceptance/ tree.
func (p *PlaywrightSupport) OutputDir(subdir string) string {
	base := "gtms/scripts/playwright"
	subdir = strings.TrimRight(subdir, "/")
	if subdir == "" {
		return base
	}
	return base + "/" + subdir
}

// GenerateSkeleton writes a minimal Playwright .spec.ts skeleton to outPath.
// The TC ID is stamped into the test title and a header comment so the
// "no other .spec.ts contains this TC content" detector in BUG-111 specs
// (tc-a575fc7a step 9) can prove starter uniqueness per TC.
func (p *PlaywrightSupport) GenerateSkeleton(tcID, projectRoot, outPath string) error {
	skeleton := fmt.Sprintf(`// Auto-generated by gtms automate --adapter agent-automate
// Test case: %s

import { test, expect } from '@playwright/test';

test('%s: <describe what this test validates>', async ({ page }) => {
  // TODO: fill in the test body
  test.skip(true, 'skeleton -- not yet implemented');
});
`, tcID, tcID)

	return os.WriteFile(outPath, []byte(skeleton), 0644)
}
